### PR TITLE
fix unCamelcase

### PR DESCRIPTION
**Pull request by ljwrer**
if text contains number,like i18n,expect to get i18n rather than i-1-8n #15

### CODE REVIEW

**Comment by demsking** [comment]
Thanks @ljwrer for your feedback. Could you just add a test that cover this case please?
Something like:

```js
it('should succeed with entry that contains numbers', () => {
  const entry = 'i18n'
  const result = utils.unCamelcase(entry)
  const expected = 'i18n'

  assert.equal(result, expected)
})
```

**Comment by demsking** [comment]
Thanks @ljwrer for your feedback. Could you just add a test that cover this case please?
Something like:

```js
it('should succeed with entry that contains numbers', () => {
  const entry = 'i18n'
  const result = utils.unCamelcase(entry)
  const expected = 'i18n'

  assert.equal(result, expected)
})
```

**Comment by ljwrer** [comment]
test case added @demsking

**Comment by demsking** [comment]
Great!
Thanks for your PR. I'll release it soon

**Pull request merged**
